# what host do we target
- hosts: localhost
  # should we gather facts for the host
  gather_facts: no
  # Ansible executes all shits with the current logged user
  # using `become` it will become root (or will sudo cmd)
  # become_user: vnj
  become: no

  # variable precedence
  # vars from command lines are the most heavy
  # playbook vars are taken first
  # then roles vars (those below)
  # then vars in `roles/app/tasks/vars/main.yaml`
  vars:
    app_port: "5002"
    root_dir: "~/tmp/kookbook"
    username: "{{ username }}"
    # username: "{{ lookup('hashi_vault', 'secrets/data/dev:username') }}"
    # password: "{{ lookup('hashi_vault', 'secrets/data/dev:password') }}"

  vars_files:
    - secrets.yaml

  tasks:
    - debug: msg={{ username }}
    - debug: msg={{ password }}

  roles:
    - role: roles/app
      vars:
        repo_name: "vanjiii/kook-book-server"
        branch_name: "master"
